apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | test app }}
  description: ${{ values.description | test app }}
spec:
  type: service
  owner: ${{ values.owner | user:guest }}
  lifecycle: experimental
